name: Deploy Hugo site 
on:
  push:
    branches: ["dev"]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.120.4
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Install Dart Sass
        run: sudo snap install dart-sass
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build with Hugo
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/"
      - name: Pack builded site
        run: cd public && zip -r ../site.zip . && cd ..
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: site.zip
          name: site

  # Deployment job
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: site
      - name: copy to wiki hosting
        run: mkdir -p .ssh && echo -e "[front.mikr.us]:5022 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG/8gsWap5DWEawOJaz5ai0ALZFMjIrMPL+mV8rCAO41\n[front.mikr.us]:5022 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBBdKmhLFCYkMxntPkefVW98xboiZnRTbpxKIyvyUvCgS3X83FTWFhlRhcjPazlq6Vcsl5sMlYlHRHHmrfFOSSnU=" > .ssh/known_hosts && echo ${{ secrets.FRONT_WIKI_SSH_KEY }} | base64 -d > .ssh/id_rsa && scp -P 5022 site.zip wiki@front.mikr.us:/var/www/wiki/ 
      
